#参照ruicky/jd

name: Github 闪挣
on:
    push:
        branches:
            - main
    schedule:
        - cron: '28 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run
              run: npm install
            - run: node sz.js
              env:
                szurl: ${{ secrets.dkdurl }}
                sckey: ${{ secrets.sckey }}
                szhd: ${{ secrets.dkdhd }}
